import { test, expect } from '@playwright/test';
const evidence = '/Users/ed/.codex/.chatgpt-projects/g-p-683c5647f32881918e942590972e90ee/output/canopy-reconciliation-20261009';
for (const width of [1440, 390, 320]) test(`Open Circle and spatial return ${width}`, async ({ page }) => {
  test.setTimeout(90000);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.setViewportSize({width,height:844});
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.route('**/*', route => {
    const request=route.request(), url=new URL(request.url());
    if (!['localhost','127.0.0.1'].includes(url.hostname) && (!['GET','HEAD'].includes(request.method()) || /\/rpc\/|\/functions\//.test(url.pathname))) return route.fulfill({contentType:'application/json',body:'[]'});
    return route.continue();
  });
  // Static UI/state seam: GPU travel is separate from accessible route/return proof.
  await page.route('**/runtime/entry.js', async route => {
    const response=await route.fetch(), source=await response.text();
    const boundary=source.indexOf('/* ---------- 3D rendering layer ---------- */');
    expect(boundary).toBeGreaterThan(0);
    await route.fulfill({response,body:source.slice(0,boundary)});
  });
  await page.goto('/council-of-life');
  const question=page.getByRole('heading',{name:'What is already blooming in us that we haven’t noticed yet?',exact:true});
  await expect(question).toBeVisible();
  const enter=page.getByRole('button',{name:'Enter the Circle →',exact:true});
  const entryBox = (await enter.boundingBox())!;
  expect(entryBox.height).toBeGreaterThanOrEqual(48);
  if (width <= 390) expect(entryBox.y + entryBox.height).toBeLessThan(780);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(page.getByText(/Earlier Council Scroll|Digital Fire and Lunar Vote|Stewardship Tools|yet to be set/)).toHaveCount(0);
  await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.images].map(i=>i.decode().catch(()=>{})));});
  await page.screenshot({path:`${evidence}/after-${width}.png`,fullPage:true});
  await page.screenshot({path:`${evidence}/arrival-${width}.png`});
  const fly=page.getByRole('button',{name:'Fly Agaric',exact:true});
  await fly.focus();await page.keyboard.press('Enter');
  await expect(fly).toHaveAttribute('aria-pressed','true');
  await expect(page.locator('#companion-reading')).toContainText('Toxic · Meet with care · Never eat.');
  await page.screenshot({path:`${evidence}/companion-${width}.png`});
  await page.getByRole('button',{name:'Follow this companion in the Circle →',exact:true}).click();
  await expect(page.frameLocator('iframe[title="TETOL Council of Life spatial deck"]').locator('#panel')).toContainText('Fly Agaric');
  await page.getByRole('button',{name:'Return to the current Circle ↑',exact:true}).click();
  await fly.click();
  await enter.focus();await page.keyboard.press('Enter');
  const frame=page.frameLocator('iframe[title="TETOL Council of Life spatial deck"]');
  await expect(frame.locator('#panel')).toContainText('What is already blooming in us');
  await frame.locator('#council-return').click();
  await expect(page.locator('iframe')).toHaveCount(0);
  await expect(enter).toBeFocused();
  await page.reload();await expect(question).toBeVisible();
  await page.getByRole('link',{name:'Follow the Council’s records →',exact:true}).click();
  await expect(page).toHaveURL(/\/council\/records/);await page.goBack();await expect(question).toBeVisible();
  await page.getByRole('button',{name:'Use Night Grove',exact:true}).click();
  await expect(page.locator('html')).toHaveClass(/dark/);
  await page.screenshot({path:`${evidence}/after-night-${width}.png`,fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.goto('/tetol/circle-235/pre-fire/tetol.html?welcome=0#croom');
  await page.locator('#council-return').click();
  await expect(page.locator('#next-gathering')).toBeInViewport();
  await expect(question).toBeVisible();
  await page.reload();await expect(question).toBeVisible();
  expect(errors).toEqual([]);
});
