/**
 * Candidate Dataset Config Shells
 *
 * Pre-registered expansion regions for the Tree Atlas Expansion Map.
 * These are scaffolded configs — not yet fully integrated datasets.
 * They follow the same DatasetConfig shape as HK and SG.
 */

import type { DatasetConfig } from "./datasetIntegration";

export const CANDIDATE_DATASET_CONFIGS: Record<string, DatasetConfig> = {
  "jp-sacred-trees": {
    key: "jp-sacred-trees",
    name: "Japan Sacred Tree & Natural Monument Register",
    countryCode: "JP",
    countryName: "Japan",
    countrySlug: "japan",
    datasetType: "sacred_trees",
    sourceUrl: "https://kunishitei.bunka.go.jp/bsys/categorylist",
    sourceOrg: "Agency for Cultural Affairs (文化庁)",
    dataFormat: "manual_curation",
    updateFrequency: "annual",
    bbox: [24, 122.9, 45.5, 153.9],
    center: { lat: 36.2, lng: 138.2 },
    defaultZoom: 5,
    flag: "🇯🇵",
    regionType: "country",
    portalTitle: "Japan — Sacred Trees & Natural Monuments",
    portalSubtitle: "Shrine guardians, mountain elders, temple courtyard trees, and living natural monuments.",
    descriptor: "Sacred Trees / Natural Monuments",
    sourceLabel: "Agency for Cultural Affairs register",
    circles: [
      { key: "shrine", label: "Shrine Guardians", icon: "⛩️", refPrefix: "JP-SH" },
      { key: "temple", label: "Temple Courtyard Trees", icon: "🏯", refPrefix: "JP-TC" },
      { key: "mountain", label: "Mountain Elders", icon: "⛰️", refPrefix: "JP-ME" },
      { key: "monument", label: "Natural Monument Giants", icon: "🌳", refPrefix: "JP-NM" },
    ],
    keySources: [
      { label: "Agency for Cultural Affairs — Natural Monuments", url: "https://kunishitei.bunka.go.jp/bsys/categorylist" },
    ],
    provenanceText: "Candidate region — multi-source discovery in progress. Records will be drawn from national natural monument registers and prefectural sacred tree inventories.",
  },

  "it-monumental-trees": {
    key: "it-monumental-trees",
    name: "Italy Monumental Trees Register (Elenco degli Alberi Monumentali)",
    countryCode: "IT",
    countryName: "Italy",
    countrySlug: "italy",
    datasetType: "monumental_trees",
    sourceUrl: "https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260",
    sourceOrg: "Ministero dell'agricoltura (MASAF)",
    dataFormat: "csv",
    updateFrequency: "annual",
    bbox: [35.5, 6.6, 47.1, 18.5],
    center: { lat: 41.9, lng: 12.5 },
    defaultZoom: 6,
    flag: "🇮🇹",
    regionType: "country",
    portalTitle: "Italy — Monumental Trees of the Peninsula",
    portalSubtitle: "Olive elders, chestnut giants, sacred oaks, and civic trees rooted in deep cultural memory.",
    descriptor: "Monumental Trees Register",
    sourceLabel: "MASAF Elenco Alberi Monumentali",
    circles: [
      { key: "olive", label: "Olive Elders", icon: "🫒", refPrefix: "IT-OE" },
      { key: "chestnut", label: "Chestnut Giants", icon: "🌰", refPrefix: "IT-CG" },
      { key: "civic", label: "Civic Monument Trees", icon: "🏛️", refPrefix: "IT-CM" },
      { key: "sacred", label: "Sacred Oaks and Cypress", icon: "🌿", refPrefix: "IT-SO" },
    ],
    keySources: [
      { label: "Elenco degli Alberi Monumentali d'Italia", url: "https://www.politicheagricole.it/flex/cm/pages/ServeBLOB.php/L/IT/IDPagina/11260" },
    ],
    provenanceText: "Candidate region — official national monumental trees register exists. Strong candidate for standard config-driven integration.",
  },

  "us-champion-trees": {
    key: "us-champion-trees",
    name: "United States Champion Trees (American Forests)",
    countryCode: "US",
    countryName: "United States",
    countrySlug: "united-states",
    datasetType: "champion_trees",
    sourceUrl: "https://www.americanforests.org/champion-trees/",
    sourceOrg: "American Forests",
    dataFormat: "open_data_portal",
    updateFrequency: "annual",
    bbox: [24.5, -125, 49.5, -66.9],
    center: { lat: 39.8, lng: -98.6 },
    defaultZoom: 4,
    flag: "🇺🇸",
    regionType: "country",
    portalTitle: "United States — Champion Trees",
    portalSubtitle: "Continental giants, desert survivors, broadleaf champions, and living state legacies.",
    descriptor: "Champion Trees",
    sourceLabel: "American Forests Champion Tree Register",
    circles: [
      { key: "conifer", label: "Conifer Giants", icon: "🌲", refPrefix: "US-CG" },
      { key: "broadleaf", label: "Broadleaf Champions", icon: "🌳", refPrefix: "US-BC" },
      { key: "desert", label: "Desert Survivors", icon: "🏜️", refPrefix: "US-DS" },
      { key: "state", label: "State Legacy Trees", icon: "🏛️", refPrefix: "US-SL" },
    ],
    keySources: [
      { label: "American Forests — National Register of Champion Trees", url: "https://www.americanforests.org/champion-trees/" },
    ],
    provenanceText: "Candidate region — clear provenance needed. National program is transitioning between organizations. Source attribution must be preserved carefully.",
  },

  "za-champion-trees": {
    key: "za-champion-trees",
    name: "South Africa Champion Trees Programme",
    countryCode: "ZA",
    countryName: "South Africa",
    countrySlug: "south-africa",
    datasetType: "champion_trees",
    sourceUrl: "https://www.dwaf.gov.za/forestry/championTrees.asp",
    sourceOrg: "DFFE / Champion Trees Project",
    dataFormat: "manual_curation",
    updateFrequency: "annual",
    bbox: [-35, 16.4, -22.1, 33],
    center: { lat: -30.6, lng: 24.0 },
    defaultZoom: 5,
    flag: "🇿🇦",
    regionType: "country",
    portalTitle: "South Africa — Champion Trees",
    portalSubtitle: "Baobab ancestors, yellowwood guardians, and landmark trees of forest, veld, and settlement.",
    descriptor: "Champion Trees",
    sourceLabel: "DFFE Champion Trees Programme",
    circles: [
      { key: "baobab", label: "Baobab Ancestors", icon: "🌍", refPrefix: "ZA-BA" },
      { key: "yellowwood", label: "Yellowwood Guardians", icon: "🌲", refPrefix: "ZA-YG" },
      { key: "fig", label: "Fig and Forest Elders", icon: "🌿", refPrefix: "ZA-FF" },
      { key: "cultural", label: "Cultural Landmark Trees", icon: "🏛️", refPrefix: "ZA-CL" },
    ],
    keySources: [
      { label: "Champion Trees — DFFE", url: "https://www.dwaf.gov.za/forestry/championTrees.asp" },
    ],
    provenanceText: "Candidate region — official champion tree programme exists. Strong candidate for direct dataset integration with high story value.",
  },

  "in-heritage-banyans": {
    key: "in-heritage-banyans",
    name: "India Heritage Banyans & Sacred Trees",
    countryCode: "IN",
    countryName: "India",
    countrySlug: "india",
    datasetType: "sacred_trees",
    sourceUrl: "https://indianbiodiversity.org/",
    sourceOrg: "India Biodiversity Portal / State Forest Departments",
    dataFormat: "manual_curation",
    updateFrequency: "static",
    bbox: [6.7, 68.1, 35.5, 97.4],
    center: { lat: 20.6, lng: 78.9 },
    defaultZoom: 5,
    flag: "🇮🇳",
    regionType: "country",
    portalTitle: "India — Heritage Banyans & Sacred Trees",
    portalSubtitle: "Banyan mandalas, temple guardians, threshold trees, and living canopies of devotion.",
    descriptor: "Heritage Banyans / Sacred Trees",
    sourceLabel: "India Biodiversity Portal / State registers",
    circles: [
      { key: "banyan", label: "Banyan Mandalas", icon: "🌳", refPrefix: "IN-BM" },
      { key: "temple", label: "Temple Guardians", icon: "🛕", refPrefix: "IN-TG" },
      { key: "village", label: "Village Threshold Trees", icon: "🏘️", refPrefix: "IN-VT" },
      { key: "ficus", label: "Sacred Ficus Elders", icon: "🌿", refPrefix: "IN-SF" },
    ],
    keySources: [
      { label: "India Biodiversity Portal", url: "https://indianbiodiversity.org/" },
    ],
    provenanceText: "Candidate region — extremely high story value. Likely requires multi-source and phased curation rather than one clean national register. Manual curation is important.",
  },

  "tw-protected-trees": {
    key: "tw-protected-trees",
    name: "Taiwan Protected & Precious Old Trees",
    countryCode: "TW",
    countryName: "Taiwan",
    countrySlug: "taiwan",
    datasetType: "ancient_trees",
    sourceUrl: "https://conservation.forest.gov.tw/",
    sourceOrg: "Forestry and Nature Conservation Agency",
    dataFormat: "open_data_portal",
    updateFrequency: "annual",
    bbox: [21.9, 120, 25.3, 122.1],
    center: { lat: 23.7, lng: 120.9 },
    defaultZoom: 7,
    flag: "🇹🇼",
    regionType: "country",
    portalTitle: "Taiwan — Protected & Precious Old Trees",
    portalSubtitle: "Temple trees, mountain elders, cypress guardians, and urban trees held in living memory.",
    descriptor: "Protected / Precious Old Trees",
    sourceLabel: "Forestry Agency old tree registry",
    circles: [
      { key: "temple", label: "Temple Trees", icon: "🏯", refPrefix: "TW-TT" },
      { key: "mountain", label: "Mountain Elders", icon: "⛰️", refPrefix: "TW-ME" },
      { key: "urban", label: "Urban Protected Trees", icon: "🏙️", refPrefix: "TW-UP" },
      { key: "cypress", label: "Cypress Guardians", icon: "🌲", refPrefix: "TW-CY" },
    ],
    keySources: [
      { label: "Forestry and Nature Conservation Agency", url: "https://conservation.forest.gov.tw/" },
    ],
    provenanceText: "Candidate region — national old-tree preservation framework exists. Many county and city protected tree datasets may need aggregation.",
  },

  "es-arboles-singulares": {
    key: "es-arboles-singulares",
    name: "Spain Árboles Singulares",
    countryCode: "ES",
    countryName: "Spain",
    countrySlug: "spain",
    datasetType: "notable_trees",
    sourceUrl: "https://www.miteco.gob.es/",
    sourceOrg: "MITECO / Autonomous Communities",
    dataFormat: "manual_curation",
    updateFrequency: "static",
    bbox: [27.6, -18.2, 43.8, 4.3],
    center: { lat: 40.4, lng: -3.7 },
    defaultZoom: 6,
    flag: "🇪🇸",
    regionType: "country",
    portalTitle: "Spain — Árboles Singulares",
    portalSubtitle: "Atlantic relics, Mediterranean elders, civic landmark trees, and island survivors.",
    descriptor: "Singular Trees",
    sourceLabel: "MITECO / regional singular tree catalogs",
    circles: [
      { key: "atlantic", label: "Atlantic Relics", icon: "🌊", refPrefix: "ES-AR" },
      { key: "mediterranean", label: "Mediterranean Elders", icon: "☀️", refPrefix: "ES-ME" },
      { key: "civic", label: "Singular Civic Trees", icon: "🏛️", refPrefix: "ES-SC" },
      { key: "island", label: "Island and Botanical Guardians", icon: "🏝️", refPrefix: "ES-IB" },
    ],
    keySources: [
      { label: "MITECO — Árboles Singulares", url: "https://www.miteco.gob.es/" },
    ],
    provenanceText: "Candidate region — strong source landscape but likely fragmented across national, regional, and municipal singular tree catalogs.",
  },

  "mx-monumental-trees": {
    key: "mx-monumental-trees",
    name: "Mexico Árboles Monumentales",
    countryCode: "MX",
    countryName: "Mexico",
    countrySlug: "mexico",
    datasetType: "monumental_trees",
    sourceUrl: "https://www.gob.mx/conafor",
    sourceOrg: "CONAFOR / SEMARNAT",
    dataFormat: "manual_curation",
    updateFrequency: "static",
    bbox: [14.5, -118.4, 32.7, -86.7],
    center: { lat: 23.6, lng: -102.5 },
    defaultZoom: 5,
    flag: "🇲🇽",
    regionType: "country",
    portalTitle: "Mexico — Árboles Monumentales",
    portalSubtitle: "Ceibas, ahuehuetes, desert elders, and sacred plaza trees woven into land and culture.",
    descriptor: "Monumental Trees",
    sourceLabel: "CONAFOR / SEMARNAT registers",
    circles: [
      { key: "ceiba", label: "Ceiba Guardians", icon: "🌳", refPrefix: "MX-CG" },
      { key: "ahuehuete", label: "Ahuehuete Elders", icon: "💧", refPrefix: "MX-AH" },
      { key: "desert", label: "Desert Monument Trees", icon: "🏜️", refPrefix: "MX-DM" },
      { key: "plaza", label: "Sacred Plaza Trees", icon: "⛪", refPrefix: "MX-SP" },
    ],
    keySources: [
      { label: "CONAFOR — National Forestry Commission", url: "https://www.gob.mx/conafor" },
    ],
    provenanceText: "Candidate region — strong cultural value. Likely discovery-led and may need manual curation or multi-source synthesis.",
  },
};
