// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.3";

// src/lib/mcp/tools/search-trees.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-trees.ts
var search_trees_default = defineTool({
  name: "search_trees",
  title: "Search ancient friends",
  description: "Search the S33D atlas of ancient trees by name, species, or nation. Returns matching trees with location and lineage.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Text to match against tree name, species, or nation."),
    limit: z.number().int().min(1).max(50).optional().describe("Maximum results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const like = `%${query.replace(/[%_,]/g, "")}%`;
    const { data, error } = await supabase.from("trees").select("id, name, species, nation, state, latitude, longitude, estimated_age, lineage").or(`name.ilike.${like},species.ilike.${like},nation.ilike.${like}`).limit(limit ?? 10);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trees: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-tree.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z2 } from "npm:zod@^3.25.76";
var get_tree_default = defineTool2({
  name: "get_tree",
  title: "Get tree with offerings",
  description: "Fetch one ancient friend by id, together with its most recent offerings (stories, art, quotes, music).",
  inputSchema: {
    tree_id: z2.string().uuid().describe("The tree's id."),
    offering_limit: z2.number().int().min(1).max(50).optional().describe("How many offerings to include (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ tree_id, offering_limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: tree, error: treeError } = await supabase.from("trees").select("*").eq("id", tree_id).maybeSingle();
    if (treeError) return { content: [{ type: "text", text: treeError.message }], isError: true };
    if (!tree) return { content: [{ type: "text", text: "No tree found with that id." }], isError: true };
    const { data: offerings, error: offeringsError } = await supabase.from("offerings").select("id, type, title, content, quote_text, quote_author, art_origin, created_at").eq("tree_id", tree_id).order("created_at", { ascending: false }).limit(offering_limit ?? 10);
    if (offeringsError) {
      return { content: [{ type: "text", text: offeringsError.message }], isError: true };
    }
    const payload = { tree, offerings: offerings ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-trees.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.3";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_trees_default = defineTool3({
  name: "list_my_trees",
  title: "List my mapped trees",
  description: "List the ancient friends the signed-in keeper has added to the atlas, newest first.",
  inputSchema: {
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("trees").select("id, name, species, nation, latitude, longitude, created_at").eq("created_by", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { trees: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/whoami.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.3";
var whoami_default = defineTool4({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in keeper's S33D profile (name, bio, home place, invite lineage).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("id, full_name, bio, home_place, invites_remaining, invites_sent, invites_accepted, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const profile = data ?? { id: ctx.getUserId(), email: ctx.getUserEmail() };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "mwzcuczfedrjplndggiv";
var mcp_default = defineMcp({
  name: "s33d",
  title: "S33D",
  version: "0.1.0",
  instructions: "Tools for S33D, a living atlas of ancient trees. Use `search_trees` to find ancient friends by name, species or nation, `get_tree` to read one tree and its offerings, `list_my_trees` for the signed-in keeper's own mapped trees, and `whoami` for their profile.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_trees_default, get_tree_default, list_my_trees_default, whoami_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.3/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
