
INSERT INTO research_trees (
  species_scientific, species_common, country, province, locality_text,
  latitude, longitude, geo_precision,
  source_program, source_doc_title, source_doc_url, source_doc_year,
  designation_type, record_kind, record_status, status, description
) VALUES
  ('Enterolobium cyclocarpum', 'Guanacaste Tree', 'Costa Rica', 'Guanacaste', 'Parque Nacional Santa Rosa',
   10.838, -85.617, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'National tree of Costa Rica, massive specimen in Santa Rosa National Park'),
  ('Ficus aurea', 'Strangler Fig', 'Costa Rica', 'Limón', 'Tortuguero National Park',
   10.543, -83.503, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Ancient Tree', 'individual_tree', 'research', 'research', 'Ancient strangler fig with aerial root system spanning 30 meters'),
  ('Ceiba pentandra', 'Ceiba', 'Costa Rica', 'Osa', 'Corcovado National Park',
   8.538, -83.591, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Ancient Tree', 'individual_tree', 'research', 'research', 'Sacred Ceiba tree, estimated 400+ years old'),
  ('Hymenaea courbaril', 'Guapinol', 'Costa Rica', 'San José', 'Valle Central',
   9.934, -84.080, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'Ancient Guapinol producing resin used by indigenous peoples'),
  ('Brosimum alicastrum', 'Breadnut', 'Costa Rica', 'Puntarenas', 'Monteverde Cloud Forest',
   10.303, -84.799, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Ecological Tree', 'individual_tree', 'research', 'research', 'Cloud forest breadnut tree, key food source for wildlife'),
  ('Dipteryx panamensis', 'Almendro', 'Costa Rica', 'Limón', 'Braulio Carrillo National Park',
   10.157, -83.951, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Ecological Tree', 'individual_tree', 'research', 'research', 'Endangered Almendro, critical nesting tree for Great Green Macaw'),
  ('Calophyllum brasiliense', 'Cedro María', 'Costa Rica', 'Heredia', 'La Selva Biological Station',
   10.432, -84.006, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'Old-growth specimen in renowned research station'),
  ('Tabebuia rosea', 'Roble de Sabana', 'Costa Rica', 'Cartago', 'Turrialba Valley',
   9.905, -83.686, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Iconic Tree', 'individual_tree', 'research', 'research', 'Magnificent flowering tree, cultural landmark'),
  ('Anacardium excelsum', 'Espavel', 'Costa Rica', 'Guanacaste', 'Palo Verde National Park',
   10.348, -85.343, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Monumental Tree', 'individual_tree', 'research', 'research', 'Giant Espavel along Tempisque River wetlands'),
  ('Cedrela odorata', 'Spanish Cedar', 'Costa Rica', 'Alajuela', 'Arenal Volcano area',
   10.463, -84.703, 'approx', 'S33D Research', 'Ancient Trees of Central America', 'https://s33d.life/research/central-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'Endangered cedar near Arenal, prized timber species under protection'),
  ('Bertholletia excelsa', 'Brazil Nut Tree', 'Peru', 'Madre de Dios', 'Tambopata National Reserve',
   -12.830, -69.296, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Ancient Tree', 'individual_tree', 'research', 'research', 'Towering Brazil nut tree, 500+ years old, critical to local economy'),
  ('Ficus insipida', 'Ojé', 'Peru', 'Loreto', 'Pacaya-Samiria National Reserve',
   -5.282, -74.532, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Ancient Tree', 'individual_tree', 'research', 'research', 'Giant Ojé fig used in traditional Amazonian medicine'),
  ('Ceiba pentandra', 'Lupuna', 'Peru', 'Ucayali', 'Upper Amazon Basin',
   -8.381, -74.530, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'Sacred Lupuna considered the world tree by Shipibo people'),
  ('Polylepis racemosa', 'Queñual', 'Peru', 'Cusco', 'Sacred Valley of the Incas',
   -13.331, -72.076, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Ecological Tree', 'individual_tree', 'research', 'research', 'High-altitude Polylepis, among worlds highest-growing trees'),
  ('Swietenia macrophylla', 'Caoba', 'Peru', 'Madre de Dios', 'Manu National Park',
   -12.268, -71.004, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Champion Tree', 'individual_tree', 'research', 'research', 'Endangered mahogany, flagship species for forest conservation'),
  ('Cedrelinga cateniformis', 'Tornillo', 'Peru', 'San Martín', 'Alto Mayo Protected Forest',
   -5.892, -77.312, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Tallest Tree', 'individual_tree', 'research', 'research', 'Massive Tornillo, one of the tallest Amazonian trees'),
  ('Podocarpus oleifolius', 'Romerillo', 'Peru', 'Cajamarca', 'Tabaconas Namballe Sanctuary',
   -5.273, -79.326, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Ecological Tree', 'individual_tree', 'research', 'research', 'Cloud forest conifer, one of few native South American conifers'),
  ('Erythrina falcata', 'Pisonay', 'Peru', 'Cusco', 'Cusco City',
   -13.520, -71.978, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Iconic Tree', 'individual_tree', 'research', 'research', 'Ancient Pisonay in Cuscos Plaza de Armas, cultural icon'),
  ('Hevea brasiliensis', 'Shiringa', 'Peru', 'Loreto', 'Iquitos Region',
   -3.749, -73.254, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Heritage Tree', 'individual_tree', 'research', 'research', 'Historic rubber tree from the rubber boom era'),
  ('Prosopis pallida', 'Algarrobo', 'Peru', 'Lambayeque', 'Bosque de Pómac Historic Sanctuary',
   -6.466, -79.805, 'approx', 'S33D Research', 'Ancient Trees of South America', 'https://s33d.life/research/south-america', 2025,
   'Ancient Tree', 'individual_tree', 'research', 'research', 'Ancient algarrobo in pre-Inca site, estimated 1000+ years');
